Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/eialidahmedjoy/.local/share/virtualenvs/radardataviewerapp-5C5sDtfg/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:9000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "/Users/jakaria/Documents/CAPSTONE/project/radarDataViewer/radarViewer/views.py", line 42, in upload_and_process_file
    return create_error_response("Failed to generate images from the data. Please try again later.", 500)
  File "/Users/jakaria/Documents/CAPSTONE/project/radarDataViewer/radarViewer/utils.py", line 10, in create_error_response
    return JsonResponse({"error": message}, status=status_code)
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/jakaria/Documents/CAPSTONE/project/radarDataViewer/radarViewer/views.py", line 52, in upload_and_process_file
    return create_error_response("An unexpected error occurred while processing the file. Please contact support if the problem persists.", 500)
  File "/Users/jakaria/Documents/CAPSTONE/project/radarDataViewer/radarViewer/utils.py", line 10, in create_error_response
    return JsonResponse({"error": message}, status=status_code)
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined
"POST /api/upload/ HTTP/1.1" 500 145
Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "/Users/jakaria/Documents/CAPSTONE/project/radarDataViewer/radarViewer/views.py", line 42, in upload_and_process_file
    return create_error_response("Failed to generate images from the data. Please try again later.", 500)
  File "/Users/jakaria/Documents/CAPSTONE/project/radarDataViewer/radarViewer/utils.py", line 10, in create_error_response
    return JsonResponse({"error": message}, status=status_code)
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/jakaria/Documents/CAPSTONE/project/radarDataViewer/radarViewer/views.py", line 52, in upload_and_process_file
    return create_error_response("An unexpected error occurred while processing the file. Please contact support if the problem persists.", 500)
  File "/Users/jakaria/Documents/CAPSTONE/project/radarDataViewer/radarViewer/utils.py", line 10, in create_error_response
    return JsonResponse({"error": message}, status=status_code)
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined
"POST /api/upload/ HTTP/1.1" 500 145
Internal Server Error: /api/upload/
"POST /api/upload/ HTTP/1.1" 500 77
Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'dict'>`
"POST /api/upload/ HTTP/1.1" 500 145
Internal Server Error: /api/upload/
"POST /api/upload/ HTTP/1.1" 500 116
Internal Server Error: /api/upload/
"POST /api/upload/ HTTP/1.1" 500 116
Internal Server Error: /api/upload/
"POST /api/upload/ HTTP/1.1" 500 116
Internal Server Error: /api/upload/
"POST /api/upload/ HTTP/1.1" 500 116
Internal Server Error: /api/upload/
"POST /api/upload/ HTTP/1.1" 500 116
Internal Server Error: /api/upload/
"POST /api/upload/ HTTP/1.1" 500 116
Internal Server Error: /api/upload/
"POST /api/upload/ HTTP/1.1" 500 116
Internal Server Error: /api/upload/
"POST /api/upload/ HTTP/1.1" 500 116
Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jakaria/.local/share/virtualenvs/project-UJpDbUi0/lib/python3.13/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'dict'>`
"POST /api/upload/ HTTP/1.1" 500 145
